### ISSUE TITLE
Page Constance Fournier

### ISSUE THREAD

**Issue by kazes** [kazes/berenicek2015#20]

**Comment by kazes** [comment]
wording : Le texte est celui de l'uad dans le premier bloc "vitrine"

**Comment by berenicek** [comment]
Texte pour "vitrine" : Création d’une identité web pour le site vitrine, écrin pour les shootings de collection et la vidéo de présentation de Constance Fournier.

**Comment by kazes** [comment]
ok c'est à jour merci

**Comment by kazes** [comment]
à tester : 
http://berenicek.com/projet-constance-fournier.php
