### ISSUE TITLE
Home > box uad

### ISSUE THREAD

**Issue by berenicek** [kazes/berenicek2015#21]
Je vois une démarquation autour de l'ordinateur sur la 1ere box de la home, il y avait un léger dégradé dedans, si tu le vires ça ne me dérange pas mais il faut retoucher le visuel alors ?

**Comment by berenicek** [comment]
Egalement dans cette box, il y a un espace en trop avant la 1ère virgule.

**Comment by kazes** [comment]
* wording corrigé
* image refaite avec transparence
